sudo: required
language: android
android:
 components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-23
before_script:
 - cd PowerUp
 - chmod +x gradlew
script:
 - ./gradlew assembleDebug
